netlify/eslint-config-node

- .eslintrc.js
Related to https://github.com/netlify/cli/pull/1479
> fix: add 202 status code to list

- CONTRIBUTING.md
This adds docs for releasing this repository.
> Add release docs

- .eslintrc.js
See https://github.com/goldbergyoni/nodebestpractices#-212-always-await-promises-before-returning-to-avoid-a-partial-stacktrace
@ehmicky thoughts?
> fix(linting): remove `no-return-await` rule

- package.json
Adds a publish script to push the relevant version change commit and tag
**Checklist**
> chore(publish): add publish script to git push version change and tag

- README.md
This updates some outdated information in `README.md`.
> Update `README.md` outdated information

- README.md
- package-lock.json
- package.json
Follow up on https://github.com/netlify/zip-it-and-ship-it/pull/265#pullrequestreview-553734579
> feat: document commit linting

- .github/workflows/release-please.yml
- CONTRIBUTING.md
- package.json
> chore: add release PR flow

- README.md
- react_config.js
- vanilla_js_config.js
Fixes https://github.com/netlify/eslint-config-node/issues
> feat: add browser configs

- .eslintrc.js
This removes some dead comment.
> Remove dead comment

- .eslintrc.js
The latest ESLint plugin major upgrade included some breaking changes. This PR fixes those.
> Fix Unicorn ESLint plugin upgrade

- .github/workflows/labeler.yml
Auto label PRs based on the title
> chore: add PR labeler action

- README.md
- package.json
Related to netlify/team-dev#7 and npm/cli#2609
> chore: fix linting and formatting on npm@7

- README.md
Add `husky@4` to the `npm install` instruction
> fix: add husky to readme

- bin/run_ci.js
- bin/run_local.js
- package-lock.json
- package.json
Fixes https://github.com/netlify/eslint-config-node/issues/140
**Checklist**
> feat: add run-ci and run-local bins

- .github/workflows/release-please.yml
- .github/workflows/workflow.yml
- test/main.js
Part of https://github.com/netlify/team-dev/issues/19
This runs the CI on the `latest` Node.js version.
> chore: run CI on latest Node.js

- test/main.js
This removes some dead code now that the upstream bug has been fixed.
> chore: remove dead code

- .eslintrc.js
- package-lock.json
- package.json
This adds more status codes to `no-magic-numbers`.
> feat: add more status codes to `no-magic-numbers`

- .eslintrc.js
This improves linting of ES modules.
> fix: add ES modules linting

- renovate.json5
This enables automerge with Renovate.
> chore: use `automerge` with Renovate

- package.json
🎉 Thanks for sending this pull request! 🎉
Please make sure the title is clear and descriptive.
If you are fixing a typo or documentation, please skip these instructions.
Otherwise please fill in the sections below.
Example: I'm always frustrated when [...]
Example: This fixes #5012
Example: I've fixed this by [...]
Example: Another solution would be [...]
**Checklist**
> chore: clean up npm files section

- renovate.json5
The lock file is internal to this repo anyway, so we might as well keep it updated
> chore: enable lock file maintenance
