netlify/eslint-config-node

README.md
This adds more documentation about how to add this shared configuration to new repositories.
In the future, we might want to have a GitHub template repository?
=> Add more documentation about adding to new repositories

README.md, package-lock.json, package.json
This makes some `devDependencies` production `dependencies` instead, so that consumers of this library do not need to add those to their `devDependencies`, and so that we don't need to upgrade those in a bunch of repositories.
=> Use production `dependencies` instead of `devDependencies`

.eslintrc.js
This is added some rules shared by both Netlify Build and CLI, so we can remove it from those projects.
=> Use shared rules from other projects

.github/workflows/workflow.yml, bin/report_coverage.sh, codecov.yml, package.json
This adds the Codecov Bash upload script as a binary exposed by `@netlify/eslint-config-node` so that consumers don't need to copy this file anymore in their repository.
=> Add Codecov shared settings

package-lock.json, package.json
This removes `eslint-plugin-standard`. That plugin [is deprecated](https://github.com/standard/standard/issues/1316) and not used in our ESLint configuration anyway.
This is in contrast to [`eslint-config-standard`](https://github.com/standard/eslint-config-standard) which we do use.
=> Remove `eslint-plugin-standard`

.eslintrc.js
This adds the new [`no-nonoctal-decimal-escape` ESLint rule](https://eslint.org/docs/rules/no-nonoctal-decimal-escape) added in the latest ESLint upgrade.
=> Add `no-nonoctal-decimal-escape` ESLint rule

.eslintrc.js
This adds the [`no-unsafe-optional-chaining` rule](https://eslint.org/docs/rules/no-unsafe-optional-chaining) which was added by the latest version of ESLint. 
We cannot use optional chaining yet until we drop support for Node 12, but this is a good rule to add for the future, and it does not hurt to add it already.
=> Add `no-unsafe-optional-chaining` ESLint rule

.eslintrc.js
This adds the [`prefer-arrow-callback` ESLint rule](https://eslint.org/docs/rules/prefer-arrow-callback).
This rule was previously incompatible with `eslint-config-prettier` and Prettier, but that's not the case anymore with its latest version.
=> Add `prefer-arrow-callback` ESLint rule

.eslintrc.js
This adds the [`arrow-body-style` ESLint rule](https://eslint.org/docs/rules/arrow-body-style).
This rule was previously in conflict with `eslint-config-prettier`, but not anymore with the latest version.
This rule turns `(args) => { return value }` into `(args) => value`. It autofixes all warnings.
=> Add `arrow-body-style` ESLint rule

.eslintrc.js
This PR tweaks the `no-magic-numbers` rule to add `429` HTTP status code.
=> Add `429` to `no-magic-numbers`

.eslintrc.js
This allows magic numbers in Markdown documentation.
=> Allow magic numbers in `README.md`

package.json
Follow up on https://github.com/netlify/eslint-config-node/pulls?q=is%3Apr+is%3Aclosed
=> fix: add missing linting configurations

react_config.js
This rule conflicts with `import/extensions`
=> fix(eslint-react): disable unicorn/import-index

package-lock.json, package.json
This upgrades [`eslint-plugin-unicorn`](https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v26.0.0) to `26.0.0`.
=> Upgrade Unicorn plugin to `26.0.0`

.eslintrc.js, package-lock.json, package.json
We don't use `eslint-plugin-prettier`. Instead we use `eslint-config-prettier` and `prettier` separately. 
So this is dead code.
=> Remove `eslint-plugin-prettier`

CONTRIBUTING.md, package.json
Add a prepublish script to further automate the release process.
Inspired by https://github.com/netlify/build/pull/2183
=> chore: add prepublish script

.eslintrc.js
This disables the [`unicorn/no-array-for-each` ESLint rule](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-for-each.md) which was introduced by `eslint-plugin-unicorn@27.0.0` (https://github.com/netlify/eslint-config-node/pull/92). This rule is too restrictive. Also, there are cases where `Array.forEach()` is more readable than a more loop.
=> chore: disable `unicorn/no-array-for-each` ESLint rule

.eslintrc.js, package-lock.json, package.json
`babel-eslint` is deprecated - this PR switches to `@babel/eslint-parser`
**Checklist**
=> fix(deps): use @babel/eslint-parser

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, .github/workflows/fossa.yml, .github/workflows/release-please.yml, .github/workflows/workflow.yml, README.md, codecov.yml, package.json, renovate.json5
Following up on the default branch renaming `master->main`:
Related to https://github.com/netlify/team-dev/issues/6
=> chore: rename master to main

.github/workflows/release-please.yml
This adds a missing id to the `release-please` to fix `npm` publishing.
See https://github.com/netlify/eslint-config-node/runs/2217534932?check_suite_focus=true
=> chore: add missing id to release-please step

.eslintrc.js
`no-unresolved` and `no-missing-import` don't recognize the node protocol yet (e.g they error on `node:buffer`).
Related to https://github.com/netlify/gotrue-js/pull/345
=> fix: disable prefer-node-protocol

.eslintrc.js
See https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1210.
https://github.com/netlify/js-client/pull/415 and https://github.com/netlify/zip-it-and-ship-it/pull/461 are failing because of this change.
My expectation was that these rules won't be checked when the library support Node.js versions < 12.
I'm not sure this warrants an issue on the `unicorn` repo as they support Node.js >=12.
Disable the rule until we drop Node.js 12 support
Fix this in each repo
**Checklist**
=> fix: disable unicorn flat and flatmap rules

.eslintrc.js
It appears that the [latest minor update](https://github.com/netlify/eslint-config-node/pull/186) of `eslint-plugin-import` had breaking changes which is making linting fail on some repositories ([example](https://github.com/netlify/js-client/pull/426/checks?check_run_id=2596497044)).
This PR fixes this.
=> fix: import/extensions rule

.eslintrc.js
Follow-up on #189 to fix some rules which contradict each other when it comes to importing JSON files.
=> chore: fix importing JSON files

.eslintrc.js
This rule conflicts with https://github.com/netlify/eslint-config-node/pull/189/files
=> fix: remove file-extension-in-import

.eslintrc.js
Functional programming patterns can be contentious. They also do not always make sense, especially inside hot paths.
This PR makes `eslint-plugin-fp` opt-in instead of opt-out. I believe some repositories like `@netlify/build` strongly benefit from following functional guidelines due to the complexity of the logic there. Those repositories can opt-in by adding those ESLint rules in their `.eslintrc.js`.
=> fix: make functional programming linting opt-in

.eslintrc.js
This rule is causing some [false positives for us](https://github.com/netlify/zip-it-and-ship-it/pull/522/checks?check_run_id=2763752176#step:5:37).
We can enable it once https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1343 is resolved.
=> fix(linting): disable prefer-prototype-methods

.github/workflows/pre-release.yml, CONTRIBUTING.md
Adds a GitHub action to automate prereleases.
It doesn't have fancy changelogs or GitHub releases, but still good for testing purposes.
See branch https://github.com/netlify/eslint-config-node/tree/releases/test/4.0.0
See tag https://github.com/netlify/eslint-config-node/releases/tag/v4.0.0-test
See `npm` https://www.npmjs.com/package/@netlify/eslint-config-node
> I'll remove the tag, branch and deprecate the published package once the PR is merged
Related to https://github.com/netlify/team-dev/issues/25
**Checklist**
=> chore(ci): prelease action

.eslintrc.js
This adds some new options [from the latest version of `eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import/blob/master/CHANGELOG.md#2240---2021-08-08).
=> feat: use new options from latest version of `eslint-plugin-import`

.eslintrc.js
This disables the [`unicorn/prefer-object-from-entries` ESLint rule](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-object-from-entries.md). It is too strict (it forbids almost all `array.reduce()`) and [gets over-reported on the CLI repository](https://github.com/netlify/cli/pull/3120/checks?check_run_id=3279680274).
=> fix: disable `unicorn/prefer-object-from-entries`

.github/.kodiak.toml, renovate.json5
Better manage CI resources for dependencies PRs using Kodiak
See https://github.com/chdsbd/kodiak/issues/701#issuecomment-899352840
Implements the flow from https://github.com/chdsbd/kodiak/issues/701#issuecomment-899352840
1. Sets Kodiak to auto merge renovate patch and minor updates. Kodiak will sync those with the default branch before merging.
2. Tells renovate not to auto merge those, so those PRs don't skip the PRs queue.
3. Tells renovate to rebase PRs only when they are conflicted (instead when the are 1 commit behind the default branch).
Letting renovate rebase+automerge and waste CI …
=> chore: enable kodiak automerge by dependency type

.eslintrc.js
Fixes https://github.com/netlify/cli/issues/3280
`eslint-plugin-import` [seems to have a bug](https://github.com/import-js/eslint-plugin-import/issues?q=%22is+invalid+and+will+just+be+ignored%22) where the `node_modules` is being linted even though it is being explicitly ignored in our configuration ([through `--ignore-path .gitignore`](https://github.com/netlify/cli/blob/587e606a8701b8109ef5ea67acd69983a0744d2d/package.json#L76)).
This makes linting fail in multiple repositories.
Removing CommonJS support for the `no-cycle` rule seems to be fixing this problem.
=> fix: `import/no-cycle` rule makes linting fail in CI

.eslintrc.js, package-lock.json, package.json
Adjust the ESLint config to add TypeScript support to our projects.
=> feat: add TypeScript rules

.eslintrc.js
Dynamic imports are currently flagged as errors by our linting configuration due to a bug in `eslint-plugin-node`.
This is fixing it.
=> fix: linting for dynamic imports

.eslintrc.js, package-lock.json, package.json
This adds some linting configuration for Cypress testing files.
This was taken [from `framework-info`](https://github.com/netlify/framework-info/blob/827ab91e844f28a53dc9c6b6eb6e2e02be84b1ac/.eslintrc.js#L16). Once this is released, we can remove it there, and also remove `eslint-plugin-cypress` from that repository.
This will ensure we will Cypress testing files across our repositories and only update `eslint-plugin-cypress` in a single repository.
=> feat: add Cypress linting configuration

.eslintrc.js
Linting that currently applies to `*.js` and `*.ts` should also apply to `*.mjs`, `*.cjs`, `*.mts` and `*.cts`.
=> fix: linting `*.mjs`, `*.cjs`, `*.mts` and `*.cts`

.eslintrc.js
as discussed in today's Node Guild Sync, this rule encourages some hard-to-read workarounds, but doesn't help a lot. we agreed to disable it.
=> fix: disable no-await-in-loop

package-lock.json, package.json
eslint-config-standard does not support eslint-plugin-promise v6 yet.
Reverts #380.
The plugin should be updated later when there are no install errors, probably in #321 and after eslint-config-standard is updated to support ESLint 8.x and `eslint-plugin-promise@6`.
---
🎉 Thanks for sending this pull request! 🎉
Please make sure the title is clear and descriptive.
If you are fixing a typo or documentation, please skip these instructions.
Otherwise please fill in the sections below.
Example: I'm always frustrated when [...]
Example: This fixes #5012
Example: I've fixed this by [...]
Example: Another …
=> fix(deps): downgrade eslint-plugin-promise to v5.2.0

.husky/commit-msg, .husky/pre-commit, .husky/pre-push, README.md, package-lock.json, package.json
🎉 Thanks for sending this pull request! 🎉
Please make sure the title is clear and descriptive.
If you are fixing a typo or documentation, please skip these instructions.
Otherwise please fill in the sections below.
Example: I'm always frustrated when [...]
Example: This fixes #5012
Example: I've fixed this by [...]
Example: Another solution would be [...]
**Checklist**
=> fix(deps): update husky package to the latest

.husky/commit-msg
Since upgrading to the latest version of Husky https://github.com/netlify/eslint-config-node/pull/403, the `commitlint` Git hook is now failing with:
```
/home/user/netlify/js-client/node_modules/@commitlint/cli/lib/cli.js:112
throw err;
^
Error: Received 'HUSKY_GIT_PARAMS' as value for -E | --env, but environment variable 'HUSKY_GIT_PARAMS' is not available globally
at getEditValue (/home/user/netlify/js-client/node_modules/@commitlint/cli/lib/cli.js:273:19)
at normalizeFlags (/home/user/netlify/js-client/node_modules/@commitlint/cli/lib/cli.js:267:18)
at main (/home/user/netlify/js-client/node_modules/@commitlint/cli/lib/cli.js:147:19)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
Node.js v17.3.1
husky - commit-msg hook exited with code 1 (error)
```
Looking at …
=> fix: `commitlint` Git hook

.husky/pre-commit
We currently enforce the following Git hooks:
- `commitlint` on new commit messages
- Linting/Prettier on `git push`
https://github.com/netlify/eslint-config-node/pull/403 added a new Git hook: `npm test` on new commits.
While this is good for code quality, I believe this might not work since some of our repositories have some pretty big test suites. Running those on each commit, as opposed to each `git push` might slow us down.
This PR reverts this new Git hook. Please let me know what you think!
cc @XhmikosR 
**Checklist**
=> chore: remove `pre-commit` hook

.husky/commit-msg
In order to find `commitlint`'s binary, `npx` must be used.
**Checklist**
=> fix: add `npx` to `commitlint`

.eslintrc.js
This PR removes the rule `no-duplicate-imports`. It attempts to do the same as `import/no-duplicates`, but it does not understand TypeScript's need to have separate imports for `import type {...` and `import {...`
=> fix: remove broken duplicate rule

package.json
When using the `exports` field in `package.json`, it becomes forbidden to import files that are not explicitly declared as exported.
We have just added that field but we forgot to declare `.prettierrc.json` as exported, since consumers import it.
This is making CI tests of consumers of `@netlify/eslint-config-node` fail ([example](https://github.com/netlify/netlify-redirect-parser/runs/5038065830?check_suite_focus=true)).
**Checklist**
=> fix: missing export for Prettier configuration

.eslintrc.cjs, .eslintrc_esm.cjs, README.md, package.json
Part of https://github.com/netlify/team-dev/issues/36
Most of our repositories have migrated to pure ES modules. However, a few are still using CommonJS.
To accommodate with both and transition incrementally, this PR adds a new `.eslintrc` that contains rules specific to repositories which have migrated to pure ES modules.
Those will need to opt-in to it by switching from `require('@netlify/eslint-config-node')` to `require('@netlify/eslint-config-node/esm')`. After switching, they will also be able to clean up a few rules in their `.eslintrc`.
**Checklist**
=> feat: add ESM-specific rules

.eslintrc_esm.cjs
Omitting the file extension when using `require()` only works for `.js`, not `.cjs`. Therefore, the new ESM-specific ESLint configuration currently crashes. 
This PR fixes this.
**Checklist**
=> fix: missing file extension with ESM configuration

.eslintrc_esm.cjs, package.json
We have just added an ESM-specific configuration file.
I tried to use the new `exports` feature which allows the import name to be different from the file path being imported. However, this seems to fail with ESLint and report a "module not found" error. When making the import name mirror the imported file path, this error disappears.
Also, when merging the base ESLint configuration, I forgot to merge its `parserOptions`.
**Checklist**
=> fix: ESM-specific configuration bugs

README.md
This fixes a typo in the `README.md`.
**Checklist**
=> chore: fix typo in the `README.md`

.eslintrc.cjs
As discussed in the guild sync, we're doubling the maximum allowed complexity to see if it still bothers us afterwards. This is a breaking change, as it may make existing `eslint-disable` comments error out.
=> feat!: double max complexity
